name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: '123456'
on:
  push:
    branches:
      - dev
jobs:
  ubuntu:
    name: UbuntuVar
    runs-on: ubuntu-latest
    env:
      JOB_ENVIRONMENT_VARIABLE: '135'
    steps:
      - name: Print Env Variables for the terting.
        env:
          STEP_ENVIROMENT_VARIABLE: '654321'

        run: |
             echo "Accessing environment Variables in the run command"
             echo "$WORKSPACE_ENVIRONMENT_VARIABLE"
             echo "$JOB_ENVIRONMENT_VARIABLE"
             echo "$STEP_ENVIROMENT_VARIABLE"
             echo "- - - - - - - - - - - - - - - - - - - - - - - - - "
             echo "environmet variable in the env contenxt"
             echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
             echo "${{ JOB_ENVIRONMENT_VARIABLE }}" 
             echo "${{ STEP_ENVIROMENT_VARIABLE }}"
