name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: '123456'
on:
  push:
    branches:
      - dev
jobs:
  ubuntu:
    name: UbuntuVar
    runs-on: ubuntu-latest
    env:
      JOB_ENVIRONMENT_VARIABLE: '135'
    steps:
      - name: Print Env Variables for the terting.
        env:
          STEP_ENVIROMENT_VARIABLE: '654321'
        run: |
             echo "Accessing environment Variables in the run command"
             echo "$WORKSPACE_ENVIRONMENT_VARIABLE"
             echo "$JOB_ENVIRONMENT_VARIABLE"
             echo "$STEP_ENVIROMENT_VARIABLE"
             echo "- - - - - - - - - - - - - - - - - - - - - - - - - "
             echo "environmet variable in the env contenxt"
             echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
             echo "${{ env.JOB_ENVIRONMENT_VARIABLE }}" 
             echo "${{ env.STEP_ENVIROMENT_VARIABLE }}"

  CheckSecrets:
      name: CheckSecrets
      runs-on: ubuntu-latest
      steps: 
       - name: ConfigureAWSCredentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
       - name: Check if creds are working properly
         run: aws s3api list-buckets
