name: AutoApprovePullRequests
on:
  pull_request:
    branches:
       - dev
jobs:
  AutoApprove:
    steps:
     - name: AutoApprove
       runs-on: ubuntu-server
       if: github.actor == 'gitcommitankit'
       uses: andrewmusgrave/automatic-pull-request-review@0.0.5
       with:
        repo-token: ${{ secrets.TOKEN }}
        event: APPROVE
        body: 'Thank you dependabot 🎊'
