name: first
on: [push]
jobs:
    practicejob: 
        name: Practicejob
        runs-on: ubuntu-latest
        steps:
          - name: Practicejob
            uses: actions/checkout@v2
            with:
              repository: gitcommitankit/nodejskube
              ref: master
              path: ./testing
          - name: ls the repository
            run: |
                 ls -l testing
                 ls -l ../

